vote/api/urls.py
from django.urls import path
from vote.api import views
from knox import views as knox_views

urlpatterns = [
    path('auth/register/', views.RegisterAPI, name='api_register'),
    path('auth/login/', views.LoginAPI, name='api_login'),
    path('auth/logout/', knox_views.LogoutView.as_view(), name='api_logout'),
    path('auth/user/', views.UserAPI, name='api_user'),
    path('data_vote/', views.ListVoteAPI, name='api_data'),
    path('data_vote/<int:id_pertanyaan>/', views.DetailVoteAPI, name='api_detail'),
    path('data_vote/<int:id_pertanyaan>/<int:id_pilihan>', views.HapusPilihanAPI, name='api_hapus_pilihan'),
    path('data_vote/<int:id_pertanyaan>/vote/', views.VotingAPI, name='api_vote')
]

vote/urls.py
from django.urls import path, include
from . import views
app_name = 'vote'

urlpatterns = [
    path('api/', include('vote.api.urls')),
    path('', views.ListPertanyaan, name='ListPertanyaan'),
    path('tambah_pertanyaan', views.TambahPertanyaan, name='TambahPertanyaan'),
    path('pertanyaan/<id_pertanyaan>', views.Voting, name='Voting'),
    path('pertanyaan/<id_pertanyaan>/tambah_pilihan', views.TambahPilihan, name='TambahPilihan'),
]

voteapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vote.urls')),
]

vote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class PertanyaanModel(models.Model):
    id_pertanyaan = models.AutoField(primary_key=True, unique=True)
    pertanyaan = models.CharField(max_length=255)
    pembuat = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.pertanyaan

    @property
    def kumpulan_pilihan(self):
        return self.pilihan.all()


class PilihanModel(models.Model):
    id_pilihan = models.AutoField(primary_key=True, unique=True)
    pertanyaan = models.ForeignKey(
        PertanyaanModel, related_name='pilihan', on_delete=models.CASCADE)
    pilihan = models.CharField(max_length=255)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.pilihan

vote/api/views.py
from django.shortcuts import render, get_object_or_404

from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticated

from knox.auth import AuthToken

from vote.models import PertanyaanModel, PilihanModel
from vote.api.serializers import (PertanyaanSerializer, PilihanSerializer,
                                  PertanyaanDetailSerializer, VotingSerializer, VoteSerializer,
                                  RegisterSerializer, UserSerializer, LoginSerializer)

# Authentication
@api_view(['POST'])
def RegisterAPI(request):
    if request.method == 'POST':
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            return Response({
                'User': UserSerializer(user, context=serializer).data,
                'token': AuthToken.objects.create(user)[1]
            })
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def LoginAPI(request):
    if request.method == 'POST':
        serializer = LoginSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.validated_data
            return Response({
                'User': UserSerializer(user, context=serializer).data,
                'token': AuthToken.objects.create(user)[1]
            })
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def UserAPI(request):
    if request.method == 'GET':
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

# API
@api_view(['GET', 'POST', "DELETE"])
@permission_classes([IsAuthenticated])
def ListVoteAPI(request):
    if request.method == 'GET':
        pertanyaan = PertanyaanModel.objects.all()
        serializer = PertanyaanSerializer(pertanyaan, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PertanyaanSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        try:
            id_pertanyaaan = request.data['id_pertanyaan']
            pilihan = get_object_or_404(PertanyaanModel, pk=id_pertanyaaan)
            pilihan.delete()
            return Response({'detail': 'Deleted'})
        except KeyError:
            raise NotFound()


@api_view(['GET', 'POST', 'DELETE', 'PATCH'])
@permission_classes([IsAuthenticated])
def DetailVoteAPI(request, id_pertanyaan):
    pertanyaan = get_object_or_404(PertanyaanModel, pk=id_pertanyaan)
    if request.method == 'GET':
        serializer = PertanyaanDetailSerializer(pertanyaan)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PilihanSerializer(data=request.data)
        print(request.data)
        if serializer.is_valid():
            pilihan = serializer.save(pertanyaan=pertanyaan)
            return Response(PilihanSerializer(pilihan).data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        # try:
        #     id_pilihan = request.data['id_pilihan']
        #     pilihan = get_object_or_404(PilihanModel, pk=id_pilihan)
        #     pilihan.delete()
        #     return Response({'detail': 'Deleted'})
        # except KeyError:
        #     raise NotFound()
        pertanyaan.delete()
        return Response(status = status.HTTP_204_NO_CONTENT)
    elif request.method == 'PATCH':
        try:
            id_pilihan = request.data['id_pilihan']
            pilihan = get_object_or_404(PilihanModel, pk=id_pilihan)
            serializer = PilihanSerializer(pilihan, data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except KeyError:
            raise NotFound()


@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated])
def VotingAPI(request, id_pertanyaan):
    pertanyaan = get_object_or_404(PertanyaanModel, pk=id_pertanyaan)
    if request.method == 'GET':
        serializer = VotingSerializer(pertanyaan)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = VoteSerializer(pertanyaan, data=request.data)
        pilihan = get_object_or_404(
            PilihanModel, pk=request.data['id_pilihan'])
        if serializer.is_valid():
            serializer = VotingSerializer(pertanyaan)
            pilihan.vote += 1
            pilihan.save()
            return Response({
                "pertanyaan": serializer.data,
                "status": "Vote Sukses"
            })
        return Response(serializer.errors)

@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def HapusPilihanAPI(request, id_pertanyaan, id_pilihan):
    pertanyaan = get_object_or_404(PertanyaanModel, pk=id_pertanyaan)
    pilihan = get_object_or_404(PilihanModel, pk=id_pilihan , pertanyaan=pertanyaan)
    if request.method == 'DELETE':
        pilihan.delete()
        return Response(status = status.HTTP_204_NO_CONTENT)

vote/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import PertanyaanModel, PilihanModel
# Create your views here.


def ListPertanyaan(request):
    pertanyaan = PertanyaanModel.objects.all()
    return render(request=request,
                  template_name='html/ListPertanyaan.html',
                  context={'kumpulan_pertanyaan': pertanyaan})

def Voting(request, id_pertanyaan):
    if request.method == 'POST':
        if request.POST.get('vote'):
            id = request.POST.get('vote')
            pilihan = PilihanModel.objects.get(pk=id)
            pilihan.vote += 1
            pilihan.save()
    pertanyaan = get_object_or_404(PertanyaanModel, pk=id_pertanyaan)
    pertanyaan.kumpulanpilihan = pertanyaan.pilihan.all()
    return render(request=request,
                  template_name='html/Voting.html',
                  context= {'pertanyaan': pertanyaan, 'id': id_pertanyaan})

def TambahPertanyaan(request):
    if request.method == 'POST':
        if request.POST.get('pertanyaan'):
            pertanyaan = request.POST.get('pertanyaan')
            new = PertanyaanModel.objects.create(pertanyaan = pertanyaan)
            return redirect('vote:Voting', new.id_pertanyaan)
    return render(request=request,
                  template_name='html/TambahPertanyaan.html')

def TambahPilihan(request, id_pertanyaan):
    pertanyaan = get_object_or_404(PertanyaanModel, pk = id_pertanyaan)
    if request.method == 'POST':
        if request.POST.get('pilihan'):
            pilihan = request.POST.get('pilihan')
            PilihanModel.objects.create(pilihan = pilihan, pertanyaan = pertanyaan)
            return redirect('vote:Voting', id_pertanyaan)
    return render(request=request,
                  template_name='html/TambahPilihan.html')

vote/templates/html/ListPertanyaan.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
</head>

<body>
	<h2>List Pertanyaan</h2>
	<table>
		<tr>
			<th>No</th>
			<th>Pertanyaan</th>
			<th>Action</th>
		</tr>
	{% for pertanyaan in kumpulan_pertanyaan %}
		<tr>
			<td><h2>{{forloop.counter}}</h2></td>
			<td><h2>{{pertanyaan.pertanyaan}}</h2></td>
			<td>
				<a href="{% url 'vote:Voting' pertanyaan.id_pertanyaan %}">
					<button>Ikuti Voting</button>
				</a>
			</td>
		</tr>
	{% endfor %}
	</table>
	<a href="{% url 'vote:TambahPertanyaan' %}"><button>Tambah Soal</button></a>
</body>

</html>

vote/templates/html/TambahPertanyaan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Pertanyaan</title>
</head>
<body>
    <h2>Tambah Pertanyaan</h2>
    <form method="POST">
        {% csrf_token %}
        <textarea name="pertanyaan"></textarea>
        <input type="submit" value="Tambah Pertanyaan">
    </form>
</body>
</html>

vote/templates/html/TambahPilihan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Pertanyaan</title>
</head>
<body>
    <h2>Tambah Pilihan</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="pilihan" placeholder="Masukan Pilihan">
        <input type="submit" value="Tambah Pertanyaan">
    </form>
</body>
</html>

vote/templates/html/Voting.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <table border="0">

        <tr>
            <th colspan="3">
                <h2>{{pertanyaan.pertanyaan}}</h2>
            </th>
        </tr>
        <tr>
            <th colspan="3">Silahkan Voting</th>
        </tr>
        <form method="POST" id="voting">
        {% csrf_token %}
        {% if pertanyaan.kumpulanpilihan %}
            {% for pilihan in pertanyaan.kumpulanpilihan %}
            <tr>
                <td><h2>{{pilihan}} : </h2></td>
                <td><h2>{{pilihan.vote}}</h2></td>
                <td>
                    <button name="vote" value="{{pilihan.id_pilihan}}" type="submit" form="voting">
                        Vote
                    </button>
                </td>
            </tr>
            {% endfor %}
        {% else %}
        <tr>
            <td colspan="3"><h2 style="text-align: center;">Belum Ada Pilihan</h2></td>
        </tr>
        <tr>
            <td><h2>Silahkan Tambahkan Pilihan</h2></td>
        </tr>
        {% endif %}
        
        </form>
    </table>
    <a href="{% url 'vote:TambahPilihan' id %}"><button>Tambahkan Pilihan</button></a>
    <p>
</body>

</html>